SELECT TOP 10 * FROM [BRONZE].[WORLD_AIRCRAFT_ACCIDENT_SUMMARY];
SELECT COUNT(*) FROM [BRONZE].[WORLD_AIRCRAFT_ACCIDENT_SUMMARY];


SELECT TOP 10 * FROM [SILVER].[WORLD_AIRCRAFT_ACCIDENT_SUMMARY];
SELECT COUNT(*) FROM [SILVER].[WORLD_AIRCRAFT_ACCIDENT_SUMMARY];


SELECT DISTINCT CAST(PAX_Injuries AS INT) AS Crew_Fatalities  FROM [BRONZE].[WORLD_AIRCRAFT_ACCIDENT_SUMMARY];


SELECT REPLACE(REPLACE(REPLACE('NATRONA CO. INT. AIRPORT','.',' '),' INT ',' INTERNATIONAL '),'  ',' ');

-- QUERYY

-- SELECT COUNT(*) FROM (
SELECT WAAS_Subset_Event_Id, 
CAST(Local_Event_Date AS DATE) as Local_Event_Date,
DBO.CleanNameV1(Aircraft) as Aircraft,
DBO.CleanNameV1(Aircraft_Operator) as Aircraft_Operator,
DBO.CleanNameV1(Event_Location) as Event_Location,
CAST(Crew_Fatalities AS INT) AS Crew_Fatalities,
CAST(Crew_Injured AS INT) AS Crew_Injured, 
CAST(Crew_Aboard AS INT) AS Crew_Aboard, 
CAST(PAX_Fatalities AS INT) AS PAX_Fatalities, 
CAST(PAX_Injuries AS INT) AS  PAX_Injuries, 
CAST(PAX_Aboard AS INT) AS PAX_Aboard
FROM [BRONZE].[WORLD_AIRCRAFT_ACCIDENT_SUMMARY];

-- ) as T ;






