SELECT TOP 10 * FROM [BRONZE].[NTSB_AVIATION_DATA];
SELECT COUNT(*) FROM [BRONZE].[NTSB_AVIATION_DATA];


SELECT DISTINCT OPRTR_SCHED_DESC FROM [BRONZE].[NTSB_AVIATION_DATA]
WHERE 
TRY_CAST(EVENT_LCL_DATE AS DATE) IS NULL;


SELECT * FROM [BRONZE].[NTSB_AVIATION_DATA]
WHERE TRY_CAST(EVENT_LCL_DATE AS DATE) IS NULL;



SELECT REPLACE(REPLACE(REPLACE('NATRONA CO. INT. AIRPORT','.',' '),' INT ',' INTERNATIONAL '),'  ',' ');

-- QUERYY

-- SELECT COUNT(*) FROM (
SELECT dbo.CleanNameV1(NTSB_RPRT_NBR) AS NTSB_RPRT_NBR, 
replace(replace(replace(dbo.CleanNameV1(ACFT_REGIST_NBR),'*',''),'_',''),N'┬','') as ACFT_REGIST_NBR,
replace(replace(replace(replace(dbo.CleanNameV1(ACFT_SERIAL_NBR),'*',''),'!',''),'`',''),'''','') as ACFT_SERIAL_NBR,
CASE 
    WHEN EV_TYPE_DESC NOT IN ('INCIDENT','ACCIDENT') THEN NULL 
    ELSE EV_TYPE_DESC
END AS EV_TYPE_DESC,
CAST(EVENT_LCL_DATE AS DATE) as Event_LCL_Date,
CAST(LOC_STATE_CODE_STD AS NCHAR(2)) as LOC_STATE_CODE_STD,
dbo.CleanAirportName(dbo.CleanNameV1(ARPT_NAME_STD)) AS ARPT_NAME_STD,
CASE
    WHEN (LTRIM(SUBSTRING(FLTCNDCT_DESC,CHARINDEX(':',FLTCNDCT_DESC)+1, LEN(FLTCNDCT_DESC)))) LIKE '%NONSCHEDULED%' THEN 'NOT SCHEDULED'
    WHEN (LTRIM(SUBSTRING(FLTCNDCT_DESC,CHARINDEX(':',FLTCNDCT_DESC)+1, LEN(FLTCNDCT_DESC)))) LIKE '%SCHEDULED%' THEN 'SCHEDULED'
    WHEN (LTRIM(SUBSTRING(FLTCNDCT_DESC,CHARINDEX(':',FLTCNDCT_DESC)+1, LEN(FLTCNDCT_DESC)))) LIKE '%GENERAL AVIATION%' THEN 'GENERAL AVIATION'
    ELSE REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NULLIF(NULLIF(UPPER((LTRIM(SUBSTRING(FLTCNDCT_DESC,CHARINDEX(':',FLTCNDCT_DESC)+1, LEN(FLTCNDCT_DESC))))),''),'UNKNOWN'),
    ',',' '),'.',' '),'-',' '),'  ',' '),'  ',' '),'U S','US'),' & ',' AND ') 
END AS FLTCNDCT_DESC ,
CASE WHEN 
OPRTR_SCHED_DESC IN ('UNKNOWN') THEN NULL 
ELSE REPLACE(REPLACE(OPRTR_SCHED_DESC,'-',' '),'  ',' ')
END AS OPRTR_SCHED_DESC,
REPLACE(replace(replace(replace(replace(replace(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(OPRTR_NSDC_NAME_STD,',',' '),'.',' '),'-',' '),'''',' '),
' INC',' INCORPORATED'),' INC ',' INCORPORATED '),'(',' '),')',' '),'`',' '),'&',' '),'  ',' '),'INCORPORATEDORPORATED','INCORPORATED'),'  ',' ')
AS OPRTR_NSDC_NAME_STD, 
ACFT_NSDC_MAKE_STD,
ACFT_NSDC_MODEL_STD,
CASE 
WHEN PATINDEX('%[^A-Z 0-9]%',ACFT_NSDC_series_STD) > 0 THEN 'UNDESIGNATED SERIES'
WHEN ACFT_NSDC_SERIES_STD LIKE '%UNDES%'  OR REPLACE(ACFT_NSDC_SERIES_STD,' ','')= 'NOSERIESEXISTS' THEN 'UNDESIGNATED SERIES'
ELSE ACFT_NSDC_SERIES_STD 
END AS ACFT_NSDC_SERIES_STD,
REPORT_STATUS,
CASE 
WHEN INJURY_DESC = 'NONE' THEN NULL
ELSE INJURY_DESC
END AS INJURY_DESC,
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(FLIGHT_PHASE_DESC,'-',' '),
'(S)','S'),')',' '),'(',' '),'/',' '),'  ',' '),'  ',' ') AS FLIGHT_PHASE_DESC
FROM [BRONZE].[NTSB_AVIATION_DATA]
WHERE TRY_CAST(EVENT_LCL_DATE AS DATE) IS NOT NULL

UNION 

SELECT NTSB_RPRT_NBR, 
ACFT_REGIST_NBR, CASE 
WHEN REPLACE(ACFT_SERIAL_NBR,'"','') = '' THEN REPLACE(EV_TYPE_DESC,'"','')
ELSE REPLACE(ACFT_SERIAL_NBR,'"','')
END AS ACFT_SERIAL_NBR, 
EVENT_LCL_DATE AS EV_TYPE_DESC, 
CAST(LOC_STATE_CODE_STD AS DATE) as Event_LCL_Date,
CAST(ARPT_NAME_STD AS NCHAR(2)) as LOC_STATE_CODE_STD,
FLTCNDCT_DESC AS APRT_NAME_STD,
LTRIM(SUBSTRING(FLTCNDCT_DESC,CHARINDEX(':',OPRTR_SCHED_DESC)+1, LEN(OPRTR_SCHED_DESC))) AS FLTCNDCT_DESC, 
OPRTR_NSDC_NAME_STD AS OPRTR_SCHED_DESC,
REPLACE(ACFT_NSDC_MAKE_STD,' INC ',' INCORPORATED ') AS OPRTR_NSDC_NAME_STD,
ACFT_NSDC_MODEL_STD AS ACFT_NSDC_MAKE_STD,
ACFT_NSDC_SERIES_STD AS ACFT_NSDC_MODEL_STD,
REPORT_STATUS AS ACFT_NSDC_SERIES_STD, 
INJURY_DESC AS REPORT_STATUS,
CASE WHEN FLIGHT_PHASE_DESC = 'NONE' THEN NULL 
ELSE FLIGHT_PHASE_DESC END AS INJURY_DESC, 
NULL AS FLIGHT_PHASE_DESC
FROM [BRONZE].[NTSB_AVIATION_DATA]
WHERE TRY_CAST(EVENT_LCL_DATE AS DATE) IS NULL;

-- ) as T ;





SELECT * FROM [SILVER].[NTSB_AVIATION_DATA];

TRUNCATE TABLE [SILVER].[NTSB_AVIATION_DATA];